# Generated by Django 2.2.5 on 2019-09-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='content_long',
        ),
        migrations.AddField(
            model_name='news',
            name='content_short',
            field=models.CharField(default='eee', max_length=300),
            preserve_default=False,
        ),
    ]
