# Generated by Django 2.2.5 on 2019-09-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20190928_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
